# App Engine Deploy Instructions: https://cloud.google.com/python/django/appengine
# Starter code: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard_python37/django
# Configuration options: https://cloud.google.com/appengine/docs/standard/python3/config/appref

# [START django_app]
runtime: python37     # TODO: Our project depends on 3.6.7, can we use this runtime?
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  SECRET_KEY: '***REMOVED***'
  VOL_DB_PASS: '***REMOVED***'
  PORT: 8080  

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /bootstrap
  static_dir: static/css/bootstrap.min.css

- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

# [END django_app]