# Generated by Django 2.1.7 on 2019-02-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(db_column='addressID', primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='street', max_length=100)),
                ('city', models.CharField(db_column='city', max_length=20)),
                ('state', models.CharField(db_column='state', max_length=20)),
                ('zipCode', models.IntegerField(db_column='zipCode')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(db_column='category', max_length=20)),
                ('categoryID', models.AutoField(db_column='categoryID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('emailID', models.AutoField(db_column='emailID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(db_column='location', max_length=20)),
                ('locationID', models.AutoField(db_column='locationID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(db_column='orgName', max_length=100)),
                ('orgID', models.AutoField(db_column='orgID', primary_key=True, serialize=False)),
                ('mission', models.TextField(db_column='missionStatement')),
                ('opportunities', models.TextField(db_column='volOpportunities')),
                ('website', models.URLField(db_column='volURL')),
                ('notes', models.TextField(db_column='notes')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phoneID', models.AutoField(db_column='phoneID', primary_key=True, serialize=False)),
                ('phone', models.CharField(db_column='phone', max_length=10)),
                ('orgid', models.ForeignKey(db_column='orgID', on_delete=django.db.models.deletion.DO_NOTHING, to='volDB.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='orgID',
            field=models.ForeignKey(db_column='orgID', on_delete=django.db.models.deletion.DO_NOTHING, to='volDB.Organization'),
        ),
        migrations.AddField(
            model_name='email',
            name='orgID',
            field=models.ForeignKey(db_column='orgID', on_delete=django.db.models.deletion.DO_NOTHING, to='volDB.Organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='orgID',
            field=models.ForeignKey(db_column='orgID', on_delete=django.db.models.deletion.DO_NOTHING, to='volDB.Organization'),
        ),
        migrations.AddField(
            model_name='address',
            name='orgID',
            field=models.ForeignKey(db_column='orgID', on_delete=django.db.models.deletion.DO_NOTHING, to='volDB.Organization'),
        ),
    ]
