# Generated by Django 2.1.7 on 2019-03-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='orgid',
            new_name='orgID',
        ),
        migrations.RemoveField(
            model_name='category',
            name='orgID',
        ),
        migrations.RemoveField(
            model_name='location',
            name='orgID',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='category', to='volDB.Category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='isVisible',
            field=models.BooleanField(db_column='visible', default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ManyToManyField(blank=True, db_column='location', to='volDB.Location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(db_column='zipCode', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, db_column='notes'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='opportunities',
            field=models.TextField(blank=True, db_column='volOpportunities'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(db_column='phone', max_length=20),
        ),
    ]
