# Generated by Django 2.1.7 on 2019-02-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0002_auto_20190224_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='organization',
            name='isVisible',
            field=models.BooleanField(db_column='visible', default=True),
        ),
    ]
