# Generated by Django 2.1.7 on 2019-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0002_auto_20190328_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.IntegerField(db_column='zipCode'),
        ),
    ]
