# Generated by Django 2.1.7 on 2019-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0003_auto_20190225_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='orgID',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(db_column='category', to='volDB.Category'),
        ),
    ]
