# Generated by Django 2.1.7 on 2019-02-25 22:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0004_auto_20190225_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Abuse'), (2, 'Activism'), (3, 'Public Policy')], db_column='category', max_length=5),
        ),
    ]
