# Generated by Django 2.1.7 on 2019-02-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0005_auto_20190225_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
