# Generated by Django 2.1.7 on 2019-02-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0006_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(choices=[(1, 'Abuse'), (2, 'Activism'), (3, 'Public Policy')], db_column='category', max_length=20)),
                ('categoryID', models.AutoField(db_column='categoryID', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='category', to='volDB.Category'),
        ),
    ]
