# Generated by Django 2.1.7 on 2019-04-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0007_auto_20190402_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='orgID',
            field=models.ForeignKey(db_column='orgID', on_delete=django.db.models.deletion.DO_NOTHING, to='volDB.Organization'),
        ),
    ]
