# Generated by Django 2.1.7 on 2019-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0007_auto_20190226_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='orgID',
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ManyToManyField(blank=True, db_column='location', to='volDB.Location'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_column='category', max_length=20),
        ),
    ]
