# Generated by Django 2.1.7 on 2019-04-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0008_auto_20190402_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='isPhysicalAddress',
        ),
    ]
