# Generated by Django 2.1.7 on 2019-04-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0009_remove_address_isphysicaladdress'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isPhysicalAddress',
            field=models.BooleanField(db_column='isPhysicalAddress', default=False),
        ),
    ]
