# Generated by Django 2.1.7 on 2019-04-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0010_address_isphysicaladdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_column='category', max_length=50),
        ),
    ]
