# Generated by Django 2.1.7 on 2019-04-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0011_auto_20190403_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(db_column='zipCode', max_length=20),
        ),
    ]
