# Generated by Django 2.1.7 on 2019-04-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0012_auto_20190403_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(db_column='phone', max_length=50),
        ),
    ]
