# Generated by Django 2.1.7 on 2019-04-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volDB', '0014_auto_20190409_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, db_column='volURL'),
        ),
    ]
